/* Builds docs/metric-digest.md from the registry, the live values captured by
 * scripts/audit-sources.mts (/tmp/metric-report.json) and the tab bindings.
 *
 *   npx tsx scripts/audit-sources.mts && npx tsx scripts/make-digest.mts
 *
 * The prose sections live in docs/metric-digest.intro.md and are prepended unchanged; everything
 * below the marker is generated, so the reference can be regenerated whenever the sheets move
 * without a human re-typing 260 rows.
 */
import fs from 'node:fs';
Object.assign(globalThis, { window: { location: { hash: '' }, innerWidth: 1600, matchMedia: () => ({ matches: false }), addEventListener() {} }, document: { documentElement: { getAttribute: () => 'matte', setAttribute() {} } }, localStorage: { getItem: () => null, setItem() {}, removeItem() {} } });
const { METRIC_LIST } = await import('../src/semantics/metrics.ts');

const live = JSON.parse(fs.readFileSync('/tmp/metric-report.json', 'utf8')) as {
  report: { table: string; id: string; label: string; formatted: string; value: number | null; n: number; coverage: number | null }[];
  findings: { sev: string; pass: string; metric: string; text: string }[];
  period: { label: string; start: string; end: string };
};
const bindings = JSON.parse(fs.readFileSync('/tmp/bindings.json', 'utf8')) as Record<string, string[]>;
const valueOf = new Map(live.report.map((r) => [r.id, r]));
const tabsFor = new Map<string, string[]>();
for (const [tab, ids] of Object.entries(bindings)) for (const id of ids) tabsFor.set(id, [...(tabsFor.get(id) ?? []), tab]);

const GRAIN: Record<string, string> = {
  visits: 'Visits — one row per member × class occurrence, reconciled from Checkins and Bookings',
  sessions: 'Sessions — one row per class occurrence',
  checkins: 'Checkins — one row per check-in',
  sales: 'Sales — one row per sale **line item**',
  newc: 'New — one row per new client',
  lapsed: 'Lapsed — one row per membership interval',
  payroll: 'Payroll — one row per trainer × month',
  leads: 'Leads — one row per enquiry',
  bookings: 'Bookings — one row per booking',
};
const AGG: Record<string, string> = {
  sum: 'sum', weighted: 'ratio of sums', avg: 'mean of rows', median: 'median of rows',
  count: 'count of matching rows', distinct: 'distinct count', custom: 'custom',
};

/* Columns the audit found present but never populated. Derived from its own findings rather than
   restated here, so the digest cannot claim a column is empty after it starts being filled. */
const emptyCols = new Set(live.findings
  .map((f) => /column "([^"]+)" is 0 on all/.exec(f.text)?.[1])
  .filter((c): c is string => !!c));
const readsEmptyColumn = (m: { sources?: string[] }) =>
  (m.sources ?? []).some((src) => emptyCols.has(src.slice(src.indexOf('.') + 1)));

const esc = (s: string) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const lines: string[] = [];
lines.push(`\n<!-- generated by scripts/make-digest.mts — do not edit below this line -->`);
lines.push(`\n# Metric reference\n`);
if (emptyCols.size) lines.push(`\n> **${emptyCols.size} source columns are present but never populated** — ${[...emptyCols].map((c) => `\`${c}\``).join(', ')}. Metrics over them are marked below and carry a caveat in the app rather than reading as a real zero.\n`);
lines.push(`${METRIC_LIST.length} metrics. Every value in the **Live** column was computed from the source sheets over **${live.period.label}** (${live.period.start} to ${live.period.end}); \`n\` is the number of rows that contributed and a coverage figure appears when some rows could not.\n`);

const byTable = new Map<string, typeof METRIC_LIST>();
for (const m of METRIC_LIST) { const a = byTable.get(m.table) ?? []; a.push(m); byTable.set(m.table, a as never); }

for (const [table, list] of [...byTable.entries()].sort()) {
  lines.push(`\n## ${GRAIN[table] ?? table}\n`);
  lines.push(`| Metric | id | Reads | How it aggregates | Live (${live.period.label}) | Shown on |`);
  lines.push(`|---|---|---|---|---|---|`);
  for (const m of [...list].sort((a, b) => a.id.localeCompare(b.id))) {
    const v = valueOf.get(m.id);
    const cols = (m.sources ?? []).map((s) => s.slice(s.indexOf('.') + 1)).join(', ');
    const cov = v?.coverage !== null && v?.coverage !== undefined && v.coverage < 0.999 ? ` · ${(v.coverage * 100).toFixed(0)}% cov` : '';
    const livecell = readsEmptyColumn(m)
      ? `**source column empty** — reads ${v ? esc(v.formatted) : '—'}, shown with a caveat in the app`
      : v ? `${esc(v.formatted)}${v.n ? ` · n=${v.n.toLocaleString('en-IN')}` : ''}${cov}` : '—';
    const tabs = (tabsFor.get(m.id) ?? []).join(', ') || '_not bound to a tab_';
    lines.push(`| **${esc(m.label)}** | \`${m.id}\` | ${esc(cols)} | ${AGG[m.aggregation]} — \`${esc(m.formula)}\` | ${livecell} | ${esc(tabs)} |`);
  }
}

/* A per-tab index, because "what is on the Retention tab" is the question people actually ask. */
lines.push(`\n## By tab\n`);
lines.push(`What each tab shows. A metric can appear on more than one tab \u2014 that is the point of a single registry, not a duplication.\n`);
for (const [tab, ids] of Object.entries(bindings).sort()) {
  const rows = ids.map((id) => ({ id, m: METRIC_LIST.find((x) => x.id === id)!, v: valueOf.get(id) })).filter((r) => r.m);
  lines.push(`\n### ${tab} \u2014 ${rows.length} metrics\n`);
  lines.push(`| Metric | id | Grain | Live (${live.period.label}) |`);
  lines.push(`|---|---|---|---|`);
  for (const r of rows.sort((a, b) => a.m.label.localeCompare(b.m.label))) {
    lines.push(`| ${esc(r.m.label)} | \`${r.id}\` | ${r.m.table} | ${r.v ? esc(r.v.formatted) : '\u2014'} |`);
  }
}

lines.push(`\n## Definitions in full\n`);
lines.push(`What each metric means, in the words the app shows beside it.\n`);
for (const [table, list] of [...byTable.entries()].sort()) {
  lines.push(`\n### ${table}\n`);
  for (const m of [...list].sort((a, b) => a.id.localeCompare(b.id))) {
    const extra: string[] = [];
    if (m.target !== undefined) extra.push(`Target ${m.target}.`);
    if (m.minSample) extra.push(`Treated as noise below ${m.minSample} rows.`);
    if (m.coverageReason) extra.push(`Coverage: ${m.coverageReason}`);
    lines.push(`- **${esc(m.label)}** (\`${m.id}\`) — ${esc(m.description)}${extra.length ? ` _${esc(extra.join(' '))}_` : ''}`);
  }
}

const intro = fs.existsSync('docs/metric-digest.intro.md') ? fs.readFileSync('docs/metric-digest.intro.md', 'utf8') : '';
fs.writeFileSync('docs/metric-digest.md', intro + lines.join('\n') + '\n');
console.log(`docs/metric-digest.md — ${METRIC_LIST.length} metrics, ${lines.length} lines generated`);
