import fs from 'node:fs';
import Papa from 'papaparse';
import { mapCheckins, mapSales, mapNew, mapLapsed, mapPayroll, deriveSessions, deriveBookings } from '../src/data/normalise.ts';
import { metricValues, rollupLevel, slotFillMap } from '../src/semantics/aggregations.ts';
const read = (f: string) => Papa.parse<Record<string,string>>(fs.readFileSync(`/tmp/${f}.csv`, 'utf8'), { header: true, skipEmptyLines: 'greedy', transformHeader: (h: string) => h.trim() }).data;
const ck = mapCheckins(read('Checkins')); const sessions = deriveSessions(ck.rows); const bookings = deriveBookings(ck.rows);
const sales = mapSales(read('Sales')); const newc = mapNew(read('New')); const todayTs = Date.UTC(2026,8,20); const lapsed = mapLapsed(read('Lapsed'), todayTs); const payroll = mapPayroll(read('Payroll'));
const ctx = { ratePerSession: 1200, todayTs, durationDefaultMin: 55, durationSuspect: ck.corruptedDurations > 0, slotFill: slotFillMap(sessions) };
console.log('corrupted durations', ck.corruptedDurations, 'sessions', sessions.length, 'bookings', bookings.length);
console.log('sessions kpis', JSON.stringify(Object.fromEntries(Object.entries(metricValues(sessions, ['sessions','seats','attendance','fill_rate','empty_sessions','rev_pas','revenue','late_cancel_rate','no_show_rate','active_slots','draw_premium_spread','top3_revenue_concentration','teaching_hours'], ctx)).map(([k,v])=>[k,v.value]))));
console.log('sales kpis', JSON.stringify(Object.fromEntries(Object.entries(metricValues(sales, ['gross_revenue','net_revenue','transactions','aov','unique_buyers','discount_rate','deferred_revenue','membership_rev_share','repeat_buyer_rate'], ctx)).map(([k,v])=>[k,v.value]))));
const fresh = newc.filter(r=>r.is_new);
console.log('new kpis', fresh.length, JSON.stringify(Object.fromEntries(Object.entries(metricValues(fresh, ['new_clients','conversion_rate','second_visit_rate','avg_conversion_span','avg_first_purchase','avg_ltv','ltv_to_first_purchase','retention_rate','survival_90'], ctx)).map(([k,v])=>[k,v.value]))));
console.log('lapsed kpis', JSON.stringify(Object.fromEntries(Object.entries(metricValues(lapsed, ['memberships','active_memberships','churn_rate','utilisation','zero_usage_memberships','dormant_actives','liability','revenue_at_risk_30d','avg_tenure_at_churn','risk_score'], ctx)).map(([k,v])=>[k,v.value]))));
console.log('payroll kpis', JSON.stringify(Object.fromEntries(Object.entries(metricValues(payroll, ['p_sessions','p_revenue','p_cost','p_margin','p_conversion_rate','payroll_pct_of_revenue'], ctx)).map(([k,v])=>[k,v.value]))));
console.log('bookings kpis', JSON.stringify(Object.fromEntries(Object.entries(metricValues(bookings, ['bookings','b_no_show_rate','b_late_cancel_rate','effective_attendance','booking_lead_time_days','same_day_share'], ctx)).map(([k,v])=>[k,v.value]))));
const t0=performance.now(); const tree = rollupLevel(lapsed, ['membership_type','location','status','member'], 0, ['memberships','churn_rate','utilisation','risk_score','l_revenue'], ctx); console.log('rollup L0 lapsed 28k rows ms', (performance.now()-t0).toFixed(1), tree.length);
const t1=performance.now(); rollupLevel(sales, ['category'], 0, ['gross_revenue','transactions','aov','discount_rate','unique_buyers','repeat_buyer_rate'], ctx); console.log('rollup sales ms', (performance.now()-t1).toFixed(1));
console.log('trainers', rollupLevel(sessions, ['trainer'], 0, ['sessions','fill_rate','draw_premium_pp'], ctx).map(n=>`${n.label}:${n.rows.length}:${(n.values.fill_rate.value!*100).toFixed(0)}%:${((n.values.draw_premium_pp.value??0)*100).toFixed(1)}pp`).join(' | '));
console.log('lapsed date sample', lapsed[100].purchase_date, lapsed[100].end_date, lapsed[100].month, 'sales sample', sales[0].date, sales[0].value, sales[0].net, 'new sample', newc[3].ltv, newc[3].memberships_used.length, newc[3].source);
